name: Run main2.py manually

on:
  workflow_dispatch:  # Allows you to trigger it from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download SpaCy model
        run: |
          python -m spacy download en_core_web_sm

      - name: Run main2.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python main2.py
